let productos = [
  {
    nombre: "Zapatillas Urbanas",
    precio: 19999,
    stock: 10,
    marca: "On Running",
    categoria: "Calzado",
    detalles: "Zapatillas deportivas con diseño urbano y suela antideslizante.",
    descripcionCorta: "Zapatillas urbanas con estilo y confort.",
    descripcionLarga: "Zapatillas deportivas diseñadas para la ciudad, con materiales de alta calidad, suela antideslizante y gran durabilidad.",
    edadDesde: "12",
    edadHasta: "60",
    foto: "https://acdn-us.mitiendanube.com/stores/001/171/785/products/salr26blc1-69e106b86ceabc9ec616851333721856-1024-1024.jpg",
    envio: true
  },
  {
    nombre: 'Remera Deportiva Mujer',
    precio: 8999,
    stock: 25,
    marca: "Nike",
    categoria: "Indumentaria",
    detalles: "Remera de secado rápido con tecnología Dri-FIT.",
    descripcionCorta: "Remera deportiva liviana y transpirable.",
    descripcionLarga: "Remera para entrenamiento con tecnología Dri-FIT que mantiene el cuerpo seco y cómodo en todo momento.",
    edadDesde: "15",
    edadHasta: "50",
    foto: "https://sevensportio.vtexassets.com/arquivos/ids/361921-800-auto?v=638538067345400000&width=800&height=auto&aspect=true",
    envio: false
  },
  {
    nombre: "Mochila Outdoor 30L",
    precio: 14999,
    stock: 5,
    marca: "The North Face",
    categoria: "Accesorios",
    detalles: "Mochila resistente al agua con múltiples compartimientos.",
    descripcionCorta: "Mochila compacta y resistente al agua.",
    descripcionLarga: "Mochila de 30 litros perfecta para actividades al aire libre, con bolsillos organizadores y resistencia a la lluvia.",
    edadDesde: "16",
    edadHasta: "65",
    foto: "https://http2.mlstatic.com/D_772542-CBT82098300287_012025-C.jpg",
    envio: true
  },
  {
    nombre: "Campera Impermeable",
    precio: 25999,
    stock: 8,
    marca: "Columbia",
    categoria: "Indumentaria",
    detalles: "Campera para lluvia con capucha y cierres sellados.",
    descripcionCorta: "Campera impermeable para todo clima.",
    descripcionLarga: "Campera con costuras selladas y tejido resistente al agua, ideal para días de lluvia y viento.",
    edadDesde: "18",
    edadHasta: "60",
    foto: "https://scandinavianar.vtexassets.com/arquivos/ids/178739-800-auto?v=638343481270430000&width=800&height=auto&aspect=true",
    envio: true
  },
  {
    nombre: "Auriculares Bluetooth",
    precio: 11999,
    stock: 30,
    marca: "JBL",
    categoria: "Electrónica",
    detalles: "Auriculares con cancelación de ruido y estuche de carga.",
    descripcionCorta: "Auriculares inalámbricos con sonido premium.",
    descripcionLarga: "Auriculares Bluetooth JBL con cancelación activa de ruido, micrófono integrado y estuche cargador.",
    edadDesde: "10",
    edadHasta: "70",
    foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5frT5kH779001DW3stUNKQLpPffgpWPQoNg&s",
    envio: false
  }
]